services:
 db:
   image: postgres
   restart: always
   environment:
     POSTGRES_PASSWORD: example
   volumes:
     - postgres-data:/var/lib/postgresql/data
 app:
   build:
     context: .
   ports:
     - 5029:80
   environment:
     - Docker_Env=Docker
   depends_on:
     - db
volumes:
 postgres-data: