// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace webapi.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("webapi.Model.Comment", b =>
                {
                    b.Property<Guid>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("PostId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CommentId");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            CommentId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaa311"),
                            Content = "comment 1",
                            CreatedAt = new DateTime(2023, 5, 4, 15, 28, 47, 34, DateTimeKind.Utc).AddTicks(9636),
                            PostId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaa211"),
                            UserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaa111")
                        },
                        new
                        {
                            CommentId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaa312"),
                            Content = "comment 2",
                            CreatedAt = new DateTime(2023, 5, 4, 15, 28, 47, 34, DateTimeKind.Utc).AddTicks(9643),
                            PostId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaa212"),
                            UserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaa112")
                        },
                        new
                        {
                            CommentId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaa313"),
                            Content = "comment 3",
                            CreatedAt = new DateTime(2023, 5, 4, 15, 28, 47, 34, DateTimeKind.Utc).AddTicks(9648),
                            PostId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaa211"),
                            UserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaa111")
                        });
                });

            modelBuilder.Entity("webapi.Model.Post", b =>
                {
                    b.Property<Guid>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaa211"),
                            Content = "user 1",
                            CreatedAt = new DateTime(2023, 5, 4, 15, 28, 47, 34, DateTimeKind.Utc).AddTicks(9592),
                            UserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaa111")
                        },
                        new
                        {
                            PostId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaa212"),
                            Content = "user 2",
                            CreatedAt = new DateTime(2023, 5, 4, 15, 28, 47, 34, DateTimeKind.Utc).AddTicks(9599),
                            UserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaa112")
                        },
                        new
                        {
                            PostId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaa213"),
                            Content = "user 3",
                            CreatedAt = new DateTime(2023, 5, 4, 15, 28, 47, 34, DateTimeKind.Utc).AddTicks(9603),
                            UserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaa113")
                        });
                });

            modelBuilder.Entity("webapi.Model.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Full_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profile_Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salt")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaa111"),
                            DateOfBirth = new DateTime(2023, 5, 4, 15, 28, 47, 34, DateTimeKind.Utc).AddTicks(9511),
                            Email = "user1@mail.com",
                            Full_Name = "user 1",
                            Password = "123",
                            Salt = 0
                        },
                        new
                        {
                            UserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaa112"),
                            DateOfBirth = new DateTime(2023, 5, 4, 15, 28, 47, 34, DateTimeKind.Utc).AddTicks(9541),
                            Email = "user2@mail.com",
                            Full_Name = "user 2",
                            Password = "123",
                            Salt = 0
                        },
                        new
                        {
                            UserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaa113"),
                            DateOfBirth = new DateTime(2023, 5, 4, 15, 28, 47, 34, DateTimeKind.Utc).AddTicks(9546),
                            Email = "user3@mail.com",
                            Full_Name = "user 3",
                            Password = "123",
                            Salt = 0
                        });
                });

            modelBuilder.Entity("webapi.WeatherForecast", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WeatherForecasts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1"),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "Test-object",
                            TemperatureC = 25
                        });
                });

            modelBuilder.Entity("webapi.Model.Comment", b =>
                {
                    b.HasOne("webapi.Model.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("webapi.Model.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("webapi.Model.Post", b =>
                {
                    b.HasOne("webapi.Model.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("webapi.Model.Post", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("webapi.Model.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
